print(peripheral.getType("botttom"))
print(peripheral.getType("top"))
print(peripheral.getType("left"))
print(peripheral.getType("right"))
print(peripheral.getType("front"))
print(peripheral.getType("back"))